### PR TITLE
Resolves #1 Add contribution guide.

### LINKED ISSUE #1: Contribution guide
Develop contribution guide to mention steps which developers can follow and develop features effectively.

### PR DESCRIPTION
**Pull request by aniketpatidar**
Resolves [#1](https://github.com/rt4914/KlinicCon-Frontend/issues/1)

### Description
This pull request adds a contribution guide.

### Type of Change
- Documentation update

### How to test this PR?
- Reviewed the `.github/CONTRIBUTING.md` file.

### CODE REVIEW

**Review by rt4914 — CHANGES_REQUESTED** [review]
Remove all these things because currently we are not allowing anyone else to contribute to this project.

Make it simple like this:

https://github.com/oppia/oppia-android/blob/develop/.github/CONTRIBUTING.md

**Comment by rt4914** [comment]
@aniketpatidar Also, you file an **issue** for creating `Contributing Guide` similar to this in Backend Repo also? Let me know if you are not comfortable in doing that.

**Review by rt4914 — CHANGES_REQUESTED** [review]
Also, can you be sure whether this file should be part of `root` folder or `.github` folder? To me `.github` make sense

**Comment by aniketpatidar** [comment]
> @aniketpatidar Also, you file an **issue** for creating `Contributing Guide` similar to this in Backend Repo also? Let me know if you are not comfortable in doing that.

Sure @rt4914 , I can definitely handle that.

**Comment by aniketpatidar** [comment]
> Also, can you be sure whether this file should be part of `root` folder or `.github` folder? To me `.github` make sense

I agree that placing the file in the .github folder makes sense. Thanks!

**Review by rt4914 — APPROVED** [review]
LGTM. Thanks.

**Pull request merged**
